title: Teste de postagem
description: >- # this means to ignore newlines until "baseurl:"
  Aqui fica a descrição de cada projeto que desenvolvi
baseurl: "myhomepage/" # the subpath of your site, e.g. /blog
url: "https://lucasfturos.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
domain: "lucasfturos.github.io"
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

