author: Lucas Felipe Turos
# baseurl: "/" # prod
baseurl: "" # dev
url: "https://lucasfturos.github.io/homepage"
domain: "lucasfturos.github.io"
encoding: UTF-8
linkedin: https://www.linkedin.com/in/lucas-felipe-turos/
github: https://github.com/lucasfturos
instagram: https://www.instagram.com/lucasfturos/
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
include:
  - _pages
  - _assets
