author: Lucas Felipe Turos
baseurl: "/" # the subpath of your site, e.g. /blog
baseurl1: "" # for test
url: "https://lucasfturos.github.io/myhomepage" # the base hostname & protocol for your site, e.g. http://example.com
domain: "lucasfturos.github.io"
encoding: UTF-8
linkedin: https://www.linkedin.com/in/lucas-felipe-turos/
github: https://github.com/lucasfturos
instagram: https://www.instagram.com/lucasfturos/
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
include:
  - _pages
  - _assets
